# Generated by Django 5.2.16 on 2026-07-20 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[("household", "Household"), ("adhoc", "Ad-hoc group")],
                        default="household",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Yard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("kinship_name", models.CharField(blank=True, max_length=50)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("pod_owner", "Pod owner"),
                            ("yard_admin", "Yard admin"),
                            ("instance_admin", "Instance admin"),
                            ("supervised", "Supervised member"),
                        ],
                        default="member",
                        max_length=16,
                    ),
                ),
                ("is_supervised", models.BooleanField(default=False)),
                ("token_generation", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "managing_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_members",
                        to="core.member",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="member",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="PodMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pod_memberships",
                        to="core.member",
                    ),
                ),
                (
                    "pod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.pod",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="member",
            name="pods",
            field=models.ManyToManyField(
                related_name="members", through="core.PodMembership", to="core.pod"
            ),
        ),
        migrations.AddField(
            model_name="pod",
            name="yards",
            field=models.ManyToManyField(related_name="pods", to="core.yard"),
        ),
        migrations.AddConstraint(
            model_name="podmembership",
            constraint=models.UniqueConstraint(fields=("member", "pod"), name="unique_member_pod"),
        ),
    ]
