# Generated by Django 5.2.16 on 2026-07-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="feed_last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
