# Generated by Django 5.2.16 on 2026-07-21 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkPreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("url", models.URLField(max_length=2000)),
                ("title", models.CharField(blank=True, max_length=300)),
                ("description", models.CharField(blank=True, max_length=600)),
                ("image_url", models.URLField(blank=True, max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_preview",
                        to="core.post",
                    ),
                ),
            ],
        ),
    ]
