# Generated by Django 5.2.16 on 2026-07-21 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_notificationpreference_reaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="pod",
            name="house_rule",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="pod",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_pods",
                to="core.member",
            ),
        ),
        migrations.CreateModel(
            name="PodMute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pod_mutes",
                        to="core.member",
                    ),
                ),
                (
                    "pod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mutes",
                        to="core.pod",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("member", "pod"), name="unique_member_pod_mute")
                ],
            },
        ),
    ]
