# Generated by Django 5.2.16 on 2026-07-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_pod_house_rule_pod_owner_podmute"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="member",
            name="address_visibility",
            field=models.CharField(
                choices=[
                    ("hidden", "No one"),
                    ("pod", "People in my pods"),
                    ("yard", "People in my yards"),
                ],
                default="hidden",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="birthday_day",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="birthday_month",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="birthday_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="member",
            name="contact_email_visibility",
            field=models.CharField(
                choices=[
                    ("hidden", "No one"),
                    ("pod", "People in my pods"),
                    ("yard", "People in my yards"),
                ],
                default="hidden",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="phone",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="member",
            name="phone_visibility",
            field=models.CharField(
                choices=[
                    ("hidden", "No one"),
                    ("pod", "People in my pods"),
                    ("yard", "People in my yards"),
                ],
                default="hidden",
                max_length=8,
            ),
        ),
    ]
