# Generated by Django 5.2.16 on 2026-07-21 03:39

import django.db.models.deletion
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_member_address_member_address_visibility_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "token",
                    models.CharField(default=core.models._media_token, max_length=43, unique=True),
                ),
                (
                    "thumbnail_token",
                    models.CharField(default=core.models._media_token, max_length=43, unique=True),
                ),
                ("image", models.ImageField(upload_to="media/full/")),
                ("thumbnail", models.ImageField(upload_to="media/thumb/")),
                ("content_type", models.CharField(max_length=32)),
                ("alt_text", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="core.post",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["post", "created_at"], name="core_mediaa_post_id_a3b9be_idx"
                    )
                ],
            },
        ),
    ]
