# Generated by Django 5.2.16 on 2026-07-21 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_digesttoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="via_email",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="InboundLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("message_id_digest", models.CharField(max_length=64)),
                ("local_part_digest", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message_id_digest", "local_part_digest"),
                        name="inbound_once_per_message_and_capability",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InboundQuarantine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("from_mismatch", "From did not match the member's address"),
                            ("no_separator", "Reply separator not found"),
                            ("malformed", "Malformed or oversized message"),
                            ("rate_limited", "Too many replies too fast"),
                        ],
                        max_length=16,
                    ),
                ),
                ("from_header", models.CharField(blank=True, max_length=254)),
                ("body_excerpt", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quarantined_mail",
                        to="core.member",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReplyAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("local_part_digest", models.CharField(max_length=64, unique=True)),
                ("minted_generation", models.PositiveIntegerField()),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reply_addresses",
                        to="core.digestissue",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reply_addresses",
                        to="core.member",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reply_addresses",
                        to="core.post",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
