# Generated by Django 5.2.16 on 2026-07-21 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_comment_via_email_inboundledger_inboundquarantine_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="digesttoken",
            name="first_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="MemberWeekPresence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("week_start", models.DateField()),
                ("present", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="week_presence",
                        to="core.member",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("member", "week_start"), name="presence_once_per_week"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PodWeekMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("week_start", models.DateField()),
                ("post_count", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="week_metrics",
                        to="core.pod",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pod", "week_start"), name="pod_metrics_once_per_week"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="YardWeekMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("week_start", models.DateField()),
                ("member_count", models.PositiveIntegerField()),
                ("wcm", models.PositiveIntegerField()),
                ("posting_breadth", models.PositiveIntegerField()),
                ("posts_in_week", models.PositiveIntegerField()),
                ("posts_responded", models.PositiveIntegerField()),
                ("catch_up_members", models.PositiveIntegerField()),
                ("digest_opens", models.PositiveIntegerField()),
                ("email_replies", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "yard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="week_metrics",
                        to="core.yard",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("yard", "week_start"), name="yard_metrics_once_per_week"
                    )
                ],
            },
        ),
    ]
