# Generated by Django 5.2.16 on 2026-07-21 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_digesttoken_first_used_at_memberweekpresence_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElderToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token_digest", models.CharField(max_length=64, unique=True)),
                ("minted_generation", models.PositiveIntegerField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elder_token",
                        to="core.member",
                    ),
                ),
            ],
        ),
    ]
