# Generated by Django 5.2.16 on 2026-07-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_eldertoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="media_kind",
            field=models.CharField(
                choices=[("photo", "Photo"), ("video", "Video")], default="photo", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="source",
            field=models.FileField(blank=True, upload_to="media/source/"),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="transcode_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("done", "Done"), ("failed", "Failed")],
                default="done",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="video",
            field=models.FileField(blank=True, upload_to="media/video/"),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="image",
            field=models.ImageField(blank=True, upload_to="media/full/"),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to="media/thumb/"),
        ),
    ]
