# Generated by Django 5.2.16 on 2026-07-22 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_mediaasset_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkpreview",
            name="image_asset",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="link_preview_image_of",
                to="core.mediaasset",
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="media_kind",
            field=models.CharField(
                choices=[("photo", "Photo"), ("video", "Video"), ("link", "Link preview")],
                default="photo",
                max_length=5,
            ),
        ),
    ]
