# Generated by Django 5.2.16 on 2026-07-22 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_linkpreview_image_asset_alter_mediaasset_media_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="moderated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_comments",
                to="core.member",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="moderated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_posts",
                to="core.member",
            ),
        ),
    ]
