# Generated by Django 5.2.16 on 2026-07-29 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_member_orientation_dismissed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="core.comment",
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="core.post",
            ),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["comment", "created_at"], name="core_mediaa_comment_4636c1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mediaasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("comment__isnull", True), ("post__isnull", False)),
                    models.Q(("comment__isnull", False), ("post__isnull", True)),
                    _connector="OR",
                ),
                name="mediaasset_exactly_one_owner",
            ),
        ),
    ]
