# Generated by Django 5.2.16 on 2026-07-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_mediaasset_on_a_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("finished_at", models.DateTimeField(auto_now_add=True)),
                ("byte_count", models.BigIntegerField()),
                ("encrypted", models.BooleanField()),
            ],
            options={
                "ordering": ["-finished_at"],
            },
        ),
        migrations.CreateModel(
            name="DomainStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("domain", models.CharField(max_length=253, unique=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name_plural": "domain statuses",
            },
        ),
    ]
