# Generated by Django 5.2.16 on 2026-08-06 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_instance_health"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="seeded_by",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name="pod",
            name="seeded_by",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name="yard",
            name="seeded_by",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="inboundquarantine",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quarantined_mail",
                to="core.member",
            ),
        ),
    ]
