# Generated by Django 5.2.16 on 2026-09-19 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_seeded_by_marker_and_quarantine_set_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="email_prompt_dismissed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="RecoveryToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token_digest", models.CharField(max_length=64, unique=True)),
                ("minted_generation", models.PositiveIntegerField()),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recovery_tokens_issued",
                        to="core.member",
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_token",
                        to="core.member",
                    ),
                ),
            ],
        ),
    ]
