# Generated by Django 5.2.16 on 2026-09-19 02:10
#
# One migration for the whole health-records change, because it has never shipped: the
# BackupRun columns below arrived in review on the same branch, and a second number would
# be an upgrade step for a schema no instance has ever had.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_seeded_by_marker_and_quarantine_set_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="backuprun",
            name="source",
            field=models.CharField(
                choices=[("scheduled", "Scheduled"), ("manual", "Manual")],
                default="manual",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="backuprun",
            name="archive_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.CreateModel(
            name="BackupFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("error", models.CharField(max_length=500)),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="CertificateStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("domain", models.CharField(max_length=253, unique=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name_plural": "certificate statuses",
            },
        ),
    ]
