# Generated by Django 5.2.17 on 2026-09-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        # One leaf, deliberately: two migrations at the same number is not a conflict git
        # can see, and Django answers it with "Conflicting migrations detected" at every
        # boot. If another branch lands a 0028 first, renumber this one on top of it.
        ("core", "0027_recovery_token_and_email_prompt"),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseholdChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("added", "Added to a household"),
                            ("removed", "Taken out of a household"),
                        ],
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="household_changes_made",
                        to="core.member",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="household_changes",
                        to="core.member",
                    ),
                ),
                (
                    "pod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="household_changes",
                        to="core.pod",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
